name: Presentation
description: Let's get a bit of background on you
body:
  - type: dropdown
    id: notification
    attributes:
      label: Notifications in GitHub setup
      description: |
        We assume that you have setup [notifications on your GitHub account](https://github.com/notifications) in such a a way, that we can communicate with you through _mentions_ and _assigmentes_ on issues - is that a fair assumption?
      options:
        - Yep - that's right, hit me!
        - No - I don't know how to set that up
      default: 0
    validations:
      required: true

  - type: dropdown
    id: markdown
    attributes:
      label: Confident in MarkDown
      description: |
        We assume that you are familiar enough with [GitHub flavoured MarkDown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) that you are confident to do this exercise and document your progress and replies here in GitHub Issues - is that a fair assumption?
      options:
        - Yep - that's right!
        - No - Wait ...eeeh! MarkDown?
      default: 0
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        Let's get a bit of background on you, so we have a discussion that takes off-set in where your are professionally right now.
        
        Go through this series of checkboxes below and check everyone where you have have acquired skill **above** the level of _novice_ implying that your would categorize yourself as either _advanced beginner_, _compentent_, _proficient_ or _expert_[^dreyfus]
        
        [^dreyfus]: The levels are refering to the [Dreyfus model of skill acqusition](https://en.wikipedia.org/wiki/Dreyfus_model_of_skill_acquisition) 

  - type: checkboxes
    id: os
    attributes:
      description: You may select more than one.
      label: Which operating systems and OS technologies have you used?
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: Docker / Orchestration   
    validations:
      required: true

  - type: checkboxes
    id: languages
    attributes:
      description: You may select more than one.
      label: Which programming languages have you used?
      options:
        - label: JavaStript/TypeScript
        - label: Java/C#
        - label: Python/Perl
        - label: Go/Rust/Dart
        - label: C/C++
    validations:
      required: true

  - type: checkboxes
    id: clouds
    attributes:
      description: You may select more than one.
      label: Which clouds or platforms have you used?
      options:
        - label: AWS/GCP/Azure
        - label: Firebase/Supabase
    validations:
      required: true
      
  - type: checkboxes
    id: testtools
    attributes:
      description: You may select more than one.
      label: Which test technologies, tools and apporoaches have you automated?
      options:
        - label: Unit tests/Static Code Analysis
        - label: Integration tests
        - label: End-to-end tests/Functional tests
        - label: Performance/Load tests
    validations:
      required: true
      
  - type: textarea
    id: in-your-own-words
    attributes:
      label: In your own words...
      description: Describe yourself from a perspective of _DevOps_ and _Software Development_
      value: |
        **Me and Devops**:
        **Me and Software Development**:
    validations:
      required: true
      
